const PROD_FIREBASE_API_KEY = '';
const PROD_FIREBASE_APP_ID = '';
const PROD_FIREBASE_MESSAGING_SENDER_ID = '';
const PROD_FIREBASE_PROJECT_ID = '';

const STAGING_FIREBASE_API_KEY = '';
const STAGING_FIREBASE_APP_ID = '';
const STAGING_FIREBASE_MESSAGING_SENDER_ID = '';
const STAGING_FIREBASE_PROJECT_ID = '';
